version: "2"
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
  - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/hatappi/gomodoro

  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/hatappi)
      - prefix(github.com/hatappi/gomodoro)

  ireturn:
    allow:
      - error
      - github.com\/gdamore\/tcell\.Screen
      - github.com\/gdamore\/tcell\/v2\.Screen
      - github.com\/mitchellh\/mapstructure\.DecodeHookFunc
      - github.com\/Khan\/genqlient\/graphql.WSConn
      - github.com\/hatappi\/gomodoro\/graph.MutationResolver
      - github.com\/hatappi\/gomodoro\/graph.QueryResolver
      - github.com\/hatappi\/gomodoro\/graph.SubscriptionResolver
      - net

  forbidigo:
    forbid:
      - '^log\..+(# Use github.com/hatappi/go-kit/log)'

  cyclop:
    max-complexity: 20

linters:
  enable-all: true
  disable:
    - wrapcheck
    - varnamelen
    - nlreturn
    - gochecknoglobals
    - err113
    - exhaustruct
    - wsl
    - funlen
    - tagliatelle
    - perfsprint
    - depguard
    # deprecated linters
    - exportloopref

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-files:
  - internal/client/graphql/generated.go
  - graph/generated.go
  - graph/model/models_gen.go

