run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-blank: false

  govet:
    enable-all: true
    shadowing: true
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/hatappi/gomodoro

  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/hatappi)
      - prefix(github.com/hatappi/gomodoro)

  ireturn:
    allow:
      - error
      - github.com\/gdamore\/tcell\.Screen
      - github.com\/mitchellh\/mapstructure\.DecodeHookFunc

  forbidigo:
    forbid:
      - '^log\..+(# Use github.com/hatappi/go-kit/log)'
    exclude_godoc_examples: false

  cyclop:
    max-complexity: 20

linters:
  enable-all: true
  disable:
    - wrapcheck
    - varnamelen
    - nlreturn
    - gochecknoglobals
    - goerr113
    - exhaustruct
    - wsl
    - funlen
    - tagliatelle
    # deprecated linters
    - scopelint
    - maligned
    - interfacer
    - exhaustivestruct
    - golint
    - deadcode
    - ifshort
    - varcheck
    - nosnakecase
    - structcheck
    - perfsprint
    - depguard

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
