version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -s
    - -w
    - -X github.com/hatappi/gomodoro/cmd.version={{.Version}}
    - -X github.com/hatappi/gomodoro/cmd.commit={{.Commit}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
release:
  github:
    owner: hatappi
    name: gomodoro
