// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type HealthStatus struct {
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
