// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

type EventCategory string

const (
	EventCategoryPomodoro EventCategory = "POMODORO"
	EventCategoryTask     EventCategory = "TASK"
)

var AllEventCategory = []EventCategory{
	EventCategoryPomodoro,
	EventCategoryTask,
}

type EventReceivedInput struct {
	EventCategory []EventCategory `json:"eventCategory"`
	EventTypes    []EventType     `json:"eventTypes"`
}

// GetEventCategory returns EventReceivedInput.EventCategory, and is useful for accessing the field via an interface.
func (v *EventReceivedInput) GetEventCategory() []EventCategory { return v.EventCategory }

// GetEventTypes returns EventReceivedInput.EventTypes, and is useful for accessing the field via an interface.
func (v *EventReceivedInput) GetEventTypes() []EventType { return v.EventTypes }

type EventType string

const (
	EventTypePomodoroStarted   EventType = "POMODORO_STARTED"
	EventTypePomodoroPaused    EventType = "POMODORO_PAUSED"
	EventTypePomodoroResumed   EventType = "POMODORO_RESUMED"
	EventTypePomodoroCompleted EventType = "POMODORO_COMPLETED"
	EventTypePomodoroStopped   EventType = "POMODORO_STOPPED"
	EventTypePomodoroTick      EventType = "POMODORO_TICK"
	EventTypeTaskCreated       EventType = "TASK_CREATED"
	EventTypeTaskUpdated       EventType = "TASK_UPDATED"
	EventTypeTaskDeleted       EventType = "TASK_DELETED"
	EventTypeTaskCompleted     EventType = "TASK_COMPLETED"
)

var AllEventType = []EventType{
	EventTypePomodoroStarted,
	EventTypePomodoroPaused,
	EventTypePomodoroResumed,
	EventTypePomodoroCompleted,
	EventTypePomodoroStopped,
	EventTypePomodoroTick,
	EventTypeTaskCreated,
	EventTypeTaskUpdated,
	EventTypeTaskDeleted,
	EventTypeTaskCompleted,
}

// OnEventReceivedEventReceivedEvent includes the requested fields of the GraphQL type Event.
type OnEventReceivedEventReceivedEvent struct {
	EventCategory EventCategory                            `json:"eventCategory"`
	EventType     EventType                                `json:"eventType"`
	Payload       OnEventReceivedEventReceivedEventPayload `json:"-"`
}

// GetEventCategory returns OnEventReceivedEventReceivedEvent.EventCategory, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEvent) GetEventCategory() EventCategory { return v.EventCategory }

// GetEventType returns OnEventReceivedEventReceivedEvent.EventType, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEvent) GetEventType() EventType { return v.EventType }

// GetPayload returns OnEventReceivedEventReceivedEvent.Payload, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEvent) GetPayload() OnEventReceivedEventReceivedEventPayload {
	return v.Payload
}

func (v *OnEventReceivedEventReceivedEvent) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*OnEventReceivedEventReceivedEvent
		Payload json.RawMessage `json:"payload"`
		graphql.NoUnmarshalJSON
	}
	firstPass.OnEventReceivedEventReceivedEvent = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Payload
		src := firstPass.Payload
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalOnEventReceivedEventReceivedEventPayload(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal OnEventReceivedEventReceivedEvent.Payload: %w", err)
			}
		}
	}
	return nil
}

type __premarshalOnEventReceivedEventReceivedEvent struct {
	EventCategory EventCategory `json:"eventCategory"`

	EventType EventType `json:"eventType"`

	Payload json.RawMessage `json:"payload"`
}

func (v *OnEventReceivedEventReceivedEvent) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *OnEventReceivedEventReceivedEvent) __premarshalJSON() (*__premarshalOnEventReceivedEventReceivedEvent, error) {
	var retval __premarshalOnEventReceivedEventReceivedEvent

	retval.EventCategory = v.EventCategory
	retval.EventType = v.EventType
	{

		dst := &retval.Payload
		src := v.Payload
		var err error
		*dst, err = __marshalOnEventReceivedEventReceivedEventPayload(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal OnEventReceivedEventReceivedEvent.Payload: %w", err)
		}
	}
	return &retval, nil
}

// OnEventReceivedEventReceivedEventPayload includes the requested fields of the GraphQL interface EventPayload.
//
// OnEventReceivedEventReceivedEventPayload is implemented by the following types:
// OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload
// OnEventReceivedEventReceivedEventPayloadEventTaskPayload
type OnEventReceivedEventReceivedEventPayload interface {
	implementsGraphQLInterfaceOnEventReceivedEventReceivedEventPayload()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) implementsGraphQLInterfaceOnEventReceivedEventReceivedEventPayload() {
}
func (v *OnEventReceivedEventReceivedEventPayloadEventTaskPayload) implementsGraphQLInterfaceOnEventReceivedEventReceivedEventPayload() {
}

func __unmarshalOnEventReceivedEventReceivedEventPayload(b []byte, v *OnEventReceivedEventReceivedEventPayload) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "EventPomodoroPayload":
		*v = new(OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload)
		return json.Unmarshal(b, *v)
	case "EventTaskPayload":
		*v = new(OnEventReceivedEventReceivedEventPayloadEventTaskPayload)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing EventPayload.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for OnEventReceivedEventReceivedEventPayload: "%v"`, tn.TypeName)
	}
}

func __marshalOnEventReceivedEventReceivedEventPayload(v *OnEventReceivedEventReceivedEventPayload) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload:
		typename = "EventPomodoroPayload"

		result := struct {
			TypeName string `json:"__typename"`
			*OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload
		}{typename, v}
		return json.Marshal(result)
	case *OnEventReceivedEventReceivedEventPayloadEventTaskPayload:
		typename = "EventTaskPayload"

		result := struct {
			TypeName string `json:"__typename"`
			*OnEventReceivedEventReceivedEventPayloadEventTaskPayload
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for OnEventReceivedEventReceivedEventPayload: "%T"`, v)
	}
}

// OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload includes the requested fields of the GraphQL type EventPomodoroPayload.
type OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload struct {
	Typename      string        `json:"__typename"`
	Id            string        `json:"id"`
	State         PomodoroState `json:"state"`
	RemainingTime int           `json:"remainingTime"`
	ElapsedTime   int           `json:"elapsedTime"`
	TaskId        string        `json:"taskId"`
	Phase         PomodoroPhase `json:"phase"`
	PhaseCount    int           `json:"phaseCount"`
}

// GetTypename returns OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload.Typename, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) GetTypename() string {
	return v.Typename
}

// GetId returns OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload.Id, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) GetId() string { return v.Id }

// GetState returns OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload.State, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) GetState() PomodoroState {
	return v.State
}

// GetRemainingTime returns OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload.RemainingTime, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) GetRemainingTime() int {
	return v.RemainingTime
}

// GetElapsedTime returns OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload.ElapsedTime, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) GetElapsedTime() int {
	return v.ElapsedTime
}

// GetTaskId returns OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload.TaskId, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) GetTaskId() string {
	return v.TaskId
}

// GetPhase returns OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload.Phase, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) GetPhase() PomodoroPhase {
	return v.Phase
}

// GetPhaseCount returns OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload.PhaseCount, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventPomodoroPayload) GetPhaseCount() int {
	return v.PhaseCount
}

// OnEventReceivedEventReceivedEventPayloadEventTaskPayload includes the requested fields of the GraphQL type EventTaskPayload.
type OnEventReceivedEventReceivedEventPayloadEventTaskPayload struct {
	Typename  string `json:"__typename"`
	Id        string `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}

// GetTypename returns OnEventReceivedEventReceivedEventPayloadEventTaskPayload.Typename, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventTaskPayload) GetTypename() string {
	return v.Typename
}

// GetId returns OnEventReceivedEventReceivedEventPayloadEventTaskPayload.Id, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventTaskPayload) GetId() string { return v.Id }

// GetTitle returns OnEventReceivedEventReceivedEventPayloadEventTaskPayload.Title, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventTaskPayload) GetTitle() string { return v.Title }

// GetCompleted returns OnEventReceivedEventReceivedEventPayloadEventTaskPayload.Completed, and is useful for accessing the field via an interface.
func (v *OnEventReceivedEventReceivedEventPayloadEventTaskPayload) GetCompleted() bool {
	return v.Completed
}

// OnEventReceivedResponse is returned by OnEventReceived on success.
type OnEventReceivedResponse struct {
	EventReceived OnEventReceivedEventReceivedEvent `json:"eventReceived"`
}

// GetEventReceived returns OnEventReceivedResponse.EventReceived, and is useful for accessing the field via an interface.
func (v *OnEventReceivedResponse) GetEventReceived() OnEventReceivedEventReceivedEvent {
	return v.EventReceived
}

type PomodoroPhase string

const (
	PomodoroPhaseWork       PomodoroPhase = "WORK"
	PomodoroPhaseShortBreak PomodoroPhase = "SHORT_BREAK"
	PomodoroPhaseLongBreak  PomodoroPhase = "LONG_BREAK"
)

var AllPomodoroPhase = []PomodoroPhase{
	PomodoroPhaseWork,
	PomodoroPhaseShortBreak,
	PomodoroPhaseLongBreak,
}

type PomodoroState string

const (
	PomodoroStateActive   PomodoroState = "ACTIVE"
	PomodoroStatePaused   PomodoroState = "PAUSED"
	PomodoroStateFinished PomodoroState = "FINISHED"
)

var AllPomodoroState = []PomodoroState{
	PomodoroStateActive,
	PomodoroStatePaused,
	PomodoroStateFinished,
}

// __OnEventReceivedInput is used internally by genqlient
type __OnEventReceivedInput struct {
	Input EventReceivedInput `json:"input"`
}

// GetInput returns __OnEventReceivedInput.Input, and is useful for accessing the field via an interface.
func (v *__OnEventReceivedInput) GetInput() EventReceivedInput { return v.Input }

// The subscription executed by OnEventReceived.
const OnEventReceived_Operation = `
subscription OnEventReceived ($input: EventReceivedInput!) {
	eventReceived(input: $input) {
		eventCategory
		eventType
		payload {
			__typename
			... on EventPomodoroPayload {
				id
				state
				remainingTime
				elapsedTime
				taskId
				phase
				phaseCount
			}
			... on EventTaskPayload {
				id
				title
				completed
			}
		}
	}
}
`

// To unsubscribe, use [graphql.WebSocketClient.Unsubscribe]
func OnEventReceived(
	ctx_ context.Context,
	client_ graphql.WebSocketClient,
	input EventReceivedInput,
) (dataChan_ chan OnEventReceivedWsResponse, subscriptionID_ string, err_ error) {
	req_ := &graphql.Request{
		OpName: "OnEventReceived",
		Query:  OnEventReceived_Operation,
		Variables: &__OnEventReceivedInput{
			Input: input,
		},
	}

	dataChan_ = make(chan OnEventReceivedWsResponse)
	subscriptionID_, err_ = client_.Subscribe(req_, dataChan_, OnEventReceivedForwardData)

	return dataChan_, subscriptionID_, err_
}

type OnEventReceivedWsResponse graphql.BaseResponse[*OnEventReceivedResponse]

func OnEventReceivedForwardData(interfaceChan interface{}, jsonRawMsg json.RawMessage) error {
	var gqlResp graphql.Response
	var wsResp OnEventReceivedWsResponse
	err := json.Unmarshal(jsonRawMsg, &gqlResp)
	if err != nil {
		return err
	}
	if len(gqlResp.Errors) == 0 {
		err = json.Unmarshal(jsonRawMsg, &wsResp)
		if err != nil {
			return err
		}
	} else {
		wsResp.Errors = gqlResp.Errors
	}
	dataChan_, ok := interfaceChan.(chan OnEventReceivedWsResponse)
	if !ok {
		return errors.New("failed to cast interface into 'chan OnEventReceivedWsResponse'")
	}
	dataChan_ <- wsResp
	return nil
}
